//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthernLightsHospital
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public decimal idAdmission { get; set; }
        public Nullable<bool> chirugieProgramme { get; set; }
        public Nullable<System.DateTime> dateAdmission { get; set; }
        public Nullable<System.DateTime> dateChirugie { get; set; }
        public Nullable<System.DateTime> dateConge { get; set; }
        public string televiseur { get; set; }
        public string telephone { get; set; }
        public string NSS { get; set; }
        public decimal numeroLit { get; set; }
        public decimal idMedecin { get; set; }
    
        public virtual Lit Lit { get; set; }
        public virtual Medecin Medecin { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
